<a href="https://colab.research.google.com/github/ManirahoJean/DATA-ANALYSIS-WITH-PYTHON/blob/main/1.NumPy/a_numparray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Arrays**

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) # start from 0 to 11 by adding 2 (even numbers), 2 = step size

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,5))  # array of zeros, 4 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)  # start from zoro up to 5 with 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4) # identity matrix, square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)  # one dimentional array of random numbers from 0 to 1

array([0.74960788, 0.98008503, 0.43011576, 0.63596254, 0.89188723])

In [17]:
np.random.rand(5,5) # 5 by 5 matrix of random numbers from 0 to 1

array([[0.73540967, 0.02171334, 0.44879318, 0.73065115, 0.3931315 ],
       [0.92751424, 0.27558249, 0.39928089, 0.93188137, 0.83462135],
       [0.4376895 , 0.45270462, 0.48353589, 0.12214647, 0.99763513],
       [0.66980975, 0.60630261, 0.90332499, 0.74036772, 0.03786808],
       [0.77940114, 0.0184673 , 0.79545492, 0.16208358, 0.19921934]])

In [18]:
np.random.randn(2) # normal distribution around zero

array([-0.76076778,  0.26073371])

In [20]:
np.random.randn(4,4)

array([[ 0.58665428,  1.66030416, -0.04848153, -1.19250618],
       [-0.44140526, -0.17370904, -0.47473946, -0.80962734],
       [ 1.31644028, -0.75252715, -0.54856139, -2.3002107 ],
       [-0.50931013, -0.26870015,  0.29980441, -0.51726983]])

In [21]:
np.random.randint(1,100) # random integer between 1 and 100, 10 and 100 excluded

93

In [22]:
np.random.randint(1,100,10) # ten random integers between 1 and 100, 1&100 excluded

array([91, 35, 85, 55, 22,  5, 20, 53, 38, 66])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([ 0, 11,  3, 27, 22, 38, 14, 26, 28, 32])

In [28]:
arr.reshape(5,5) # reshape the array. rows*columns must equal to total size

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

38

In [34]:
ranarr.min()

0

In [35]:
ranarr.argmax() # the index where max is located

5

In [36]:
ranarr.argmin() # the index where min value is located

0

In [37]:
arr.shape # show the shape of the array

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.shape

(5, 5)

In [41]:
arr.dtype # data type of the array

dtype('int64')

When you don't want to use np.randomint you can use:

In [43]:
from numpy.random import randint

In [44]:
randint(3,10)

4