<a href="https://colab.research.google.com/github/ManirahoJean/DATA-ANALYSIS-WITH-PYTHON/blob/main/1.NumPy/a_numparray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Arrays**

In [ ]:
my_list = [1,2,3]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) # start from 0 to 11 by adding 2 (even numbers)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,5))  # array of zeros, 4 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])