<a href="https://colab.research.google.com/github/ManirahoJean/DATA-ANALYSIS-WITH-PYTHON/blob/main/1.NumPy/b_numpyindexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Indexing and Selection**

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[5] # index five

5

In [6]:
arr[0:5] # index from zero to five

array([0, 1, 2, 3, 4])

In [7]:
arr[5:] # like normal python list

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100  # broadcast 100 to first five digits

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11) # rest the array

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6] # slicing an array

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] # grab everything in the array

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99 # broadcast the array

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr  # original array is affected to avoid the memory issues of thealarge array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()  # when you want a copy

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100 # broadcast 100 to the entire array

In [22]:
arr_copy  # broadcasted

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr # original array is not affected by copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Indexing 2D Arrays: Matrix**

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0][0] # row index zero and column index zero

5

In [27]:
arr_2d[0] # entire row

array([ 5, 10, 15])

In [28]:
arr_2d[2][1] # row two, column 1

40

In [29]:
arr_2d[1,2] # single bracket method, recommended

30

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[:2,1:] # grab up to row index 2 and grab from column 1 onward

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

**Array Comparison**

In [39]:
arr = np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_arr = arr > 5

In [42]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
arr[arr > 5] # Conditional selection we use all the time

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr < 3]

array([1, 2])

In [46]:
arr_2d = np.arange(0,50).reshape(5,10)

In [47]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])