<a href="https://colab.research.google.com/github/ManirahoJean/DATA-ANALYSIS-WITH-PYTHON/blob/main/1.NumPy/b_numpyindexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Indexing and Selection**

In [52]:
import numpy as np

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[5] # index five

5

In [56]:
arr[0:5] # index from zero to five

array([0, 1, 2, 3, 4])

In [57]:
arr[5:] # like normal python list

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5] = 100  # broadcast 100 to first five digits

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr = np.arange(0,11) # rest the array

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_arr = arr[0:6] # slicing an array

In [63]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_of_arr[:] # grab everything in the array

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr[:] = 99 # broadcast the array

In [66]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [67]:
arr  # original array is affected to avoid the memory issues of thealarge array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr.copy()  # when you want a copy

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:] = 100 # broadcast 100 to the entire array

In [72]:
arr_copy  # broadcasted

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr # original array is not affected by copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Indexing 2D Arrays: Matrix**

In [74]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[0][0] # row index zero and column index zero

5

In [78]:
arr_2d[0] # entire row

array([ 5, 10, 15])

In [79]:
arr_2d[2][1] # row two, column 1

40

In [80]:
arr_2d[1,2] # single bracket method, recommended

30

In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[:2,1:] # grab up to row index 2 and from column 1 onward

array([[10, 15],
       [25, 30]])